version: '3.8'

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '81:80'
    volumes:
      - .:/var/www/rewards
      - ./Docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    container_name: php
    build:
      context: ./Docker/php
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/rewards